#pragma once
enum Models {
    PLAYER_UP, PLAYER_DOWN, PLAYER_LEFT, PLAYER_RIGHT,
    BODY,
    TAIL_UP, TAIL_DOWN, TAIL_LEFT, TAIL_RIGHT,
    FOOD_BANANA, FOOD_APPLE, FOOD_WATERMELON,
    NUM_MODELS
};

enum Direction { UP, DOWN, LEFT, RIGHT };
