#pragma once
enum Models {
    PLAYER_UP, PLAYER_DOWN, PLAYER_LEFT, PLAYER_RIGHT,
    PLAYER_UP_0, PLAYER_DOWN_0, PLAYER_LEFT_0, PLAYER_RIGHT_0,
    BODY,
    TAIL_UP, TAIL_DOWN, TAIL_LEFT, TAIL_RIGHT,
    FOOD_BANANA, FOOD_APPLE, FOOD_WATERMELON, FOOD_PINEAPPLE, FOOD_PUMPKIN,
    NUM_MODELS
};

enum Direction { UP, DOWN, LEFT, RIGHT };
